[Ellyheetov] Pokergameapp step3
code-squad/swift-pokergameapp pull request #106
Opened 2021-02-15 12:40 UTC by ellyheetov

- 이전 comment를 반영하여 불필요한 함수와 주석을 제거하였습니다.
- CardDeck struct를 생성하였습니다.
- CardDeck과 관련된 기능 `shuffle`,`removeOne`,`reset`은 객체의 메소드로 작성하였습니다.
 - 실행결과는 README.md에 첨부하였습니다.
 
뭘 적어야 할지 모르겠습니다...

2021-02-15 13:06 UTC, godrm commented
와... 일주일 스텝을 하루에 다 끝내려는 건가요? 엄청난 속도로 하고 있네요.
학습정리는 하고 있는거 맞겠죠?

2021-02-15 13:07 UTC, godrm commented
> 뭘 적어야 할지 모르겠습니다...

개발하는 과정에서 커밋하기 전에 고민했던 것, 학습했던 것, 비교했던 방식인데 선택하지 않은 이유 등등
코드 결과말고 과정을 채우려고 노력해보세요. 돌아가는 코드 1개만 딱 만들려고 PR을 빨리 보내는게 아니라
어떤 과정에서 무엇을 비교해보고 선택했는지 살펴보는 게 중요해서요.

2021-02-15 13:16 UTC, godrm commented
작업할 때 새로운 브랜치를 생성하지 않는 것 같습니다. 작업 브랜치를 생성하는 습관을 가져보세요.

2021-02-15 13:28 UTC, godrm requested changes
조금 서두른 느낌이 있네요. 
다음 피드백을 확인해보시고, PR 열어놓을테니 수정해서 Push해주세요.
작업 완료하면 댓글을 남겨주시면 확인해볼게요.

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/CardViewController.swift
> +        return UIImage(named: "cardback.png")
옵셔널보다는 옵셔널이 아닌게 좋지 않을까요?

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/CardViewController.swift
> +        static let totalNumOfCards : CGFloat = 7 // 카드의 개수
Ratio.totalNumOfCards 는 뭔가 어색한데요? 비율에 카드개수가 포함되는 개념일까요?

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/CardViewController.swift
> +        let cardWidth = (self.view.bounds.maxX - self.view.bounds.minX) / (Ratio.totalNumOfCards + CGFloat(1))
`CGFloat(1)`은 어떤 의도일까요? 이것도 상수로 선언하거나 
Ratio.totalNumOfCards + CGFloat(1) 합쳐서 선언하는 게 좋지 않을까요?

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/CardViewController.swift
> +        let cardHeight = cardWidth * Ratio.cadRatio
`Ratio.cadRatio`는 어떤 의도인지 모르겠습니다. 혹시 오타일까요?

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/CardViewController.swift
> +                                                      width: cardWidth, height: cardHeight))
CGRect 에 x나 y 값을 중첩해서 작성하기 보다는 길어지면 별도로 빼는 것이 더 읽기 좋을 것 같습니다.
let 정도 사용하는 것은 컴파일 결과로 보면 차이가 없습니다.

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/PlayingCard.swift
> +        static var all : [Suit] = [.hearts, .clubs, .dimonds, .spades]
enum 값을 모두 갖고 있는 배열을 선언하는 것도 하드 코딩의 한 종류가 됩니다. 
한 가지 힌트를 주자면 enum 타입에 새로운 case가 추가되도 고쳐야 하는 곳이 더 생기면 하드코딩한 거라고 판단하면 됩니다.
CaseIterable 프로토콜에 대해 학습해보고 개선해서 Push해보세요.

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/PlayingCard.swift
> +        }
여기도 CaseIterable 프로토콜에 대해 학습해보고 개선해서 Push해보세요.

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/PlayingCardDeck.swift
> +        print("총 \(count)장의 카드가 있습니다.")
로직을 처리하는 곳, 계산하는 곳에서는 print()를 출력하지 마세요.
이렇게 구현하면 이 구조체는 iOS 앱을 만드는 용도로 만든게 아닙니다.
값만 처리하고 결과를 전달해서 출력하도록 구현하는 게 좋습니다.

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/PlayingCardDeck.swift
> +        print("총 \(count)장의 카드가 남아있습니다.")
여기도 print() 구문을 직접 출력하지 마세요. removeOne()을 호출한 상위 모듈에서 출력을 하는 게 좋습니다.

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/PlayingCardDeck.swift
> +        print("전체 \(count)장의 카드를 섞었습니다.")
suffle()? shuffle()? 단어를 확인해주세요.
여기도 print() 구문을 직접 출력하지 마세요.

2021-02-15 13:28 UTC, godrm commented on PokerGameApp/PlayingCardDeck.swift
> +    mutating func initialize(){
init 과 initialize 차이를 모르겠습니다. 하나만 있으면 안되는 걸까요?

2021-02-15 13:36 UTC, ellyheetov commented on PokerGameApp/PlayingCardDeck.swift
> +    mutating func initialize(){
init()과 initialize()를 구분해 놓은 이유는 reset() 메소드 때문이었습니다. 
rest 메소드에서는 이전에 생성 되었던 카드를 모두 지우고 다시 초기합니다. 
초기화가 한번 더 필요하게 되었고, 중복된 코드를 작성하는 것이 아닌 initialize 메소드로 도출하게 되었습니다.

2021-02-15 13:57 UTC, godrm commented on PokerGameApp/PlayingCardDeck.swift
> +    mutating func initialize(){
아하 다른곳에서도 사용하는 군요. 그러면 init()에서 reset()을 호출하는 것도 가능할까요?

2021-02-15 14:00 UTC, ellyheetov commented on PokerGameApp/PlayingCardDeck.swift
> +    mutating func initialize(){
그게 더 좋을 것 같네요! 수정하겠습니다.

2021-02-16 02:46 UTC, godrm commented
혹시 모두 수정한거면 댓글을 남겨주세요.

2021-02-16 04:43 UTC, ellyheetov commented
shuffle 함수 구현 및 테스트 코드 작성하여 댓글 달도록 하겠습니다. 조금 오래걸릴 것 같아요 :)

2021-02-16 05:53 UTC, ellyheetov commented on PokerGameApp/CardViewController.swift
> +        return UIImage(named: "cardback.png")
UIImage()로 가져 온 이후의 결과가 Optional type이기 때문에 cardImage도 Optional 타입으로 지정하였습니다. 
Optional이 아닌 것으로 하기 위해서는 두가지 방안이 있을 것 같은데,
1. throw로 예외처리
2. UIImage(named:) ?? something (something자리에 뭐가 들어가야 할지 모르겠습니다)

어떻게 코드를 수정해야할지 질문드립니다.

2021-02-16 05:55 UTC, godrm commented on PokerGameApp/CardViewController.swift
> +        return UIImage(named: "cardback.png")
속성에 대해서 throw가 되던가요?
UIImage 타입인데 에러가 안나려면 어떤 값이 필요할까요?

2021-02-16 06:02 UTC, ellyheetov commented on PokerGameApp/CardViewController.swift
> +        return UIImage(named: "cardback.png")
UIImage는 별도의 파라미터 없이 생성할 수 있는 클래스군요.
UIImage() 를 return 하면 될까요?

2021-02-16 06:05 UTC, godrm commented on PokerGameApp/CardViewController.swift
> +        return UIImage(named: "cardback.png")
return 할 게 뭔지 저한테 확인할 필요는 없습니다. 스스로 납득할 만한 기준에 맞춰서 선택하고 그걸로 다른 개발자를 설득할 수 있어야 합니다. 
제 기준에서는 UIImage() 로 충분한지, 다른 이미지를 지정하는 게 좋은지, 실수라도 옵셔널(nil)이 안되는 경우를 만들 수 있는지 등을 고려할 것 같습니다. 개발 과정에서는 제 생각대로 구현하는 것보다 본인의 기준을 정하는 게 중요합니다. 결정해보세요.

2021-02-16 06:26 UTC, ellyheetov commented
## 수정사항
- Ratio 구조체 제거 : 상수들을 모아 하나의 구조체로 저장하기 위한 목적으로 생성하였으나, Ratio 범위에 맞지 않는 다른 상수들을 포함하고 있다 -> CardViewController 클래스 내에 상수를 정의함
- CGRect에 들어가는 값이 복잡하여 따로 분리
- Nested Enum 수정 : CaseIterable 사용
- 로직을 처리하는 곳에 `print()`문 제거 -> XCTest로 분리
- init과 initialize문 개선 : init과 initialize는 결국 같은 역할 -> init()에서 reset()을 호출하고 reset에서 initialize()를 호출 하도록 변경
- UIImage Optional : Optional type 제거
- Shuffle 메소드 오타 제거 : `suffle()` -> `shuffle()`

## 고민한 것 

### Optional type으로 선언된 경우
생성하고자 하는 이미지 파일이 없다면 앱이 죽어버린다. 때문에 Optional보다는 Optional이 아닌 것이 바람직하다고 본다.

```swift
UIImage(named:) ?? UIImage()
```
위와 같이 사용하면 생성하고자 하는 이미지 파일이 없다면 빈 UIImage  객체를 반환한다. 사용자에 입장에서는 해당 이미지가 보이지 않을 뿐 앱이 종료되지 않는다. 

### XCTest
앱을 만드는 프로젝트이지만, console에 print문을 찍는 목적은 구현한 함수가 잘 동작하는지 눈으로 확인 하는데 에 있다.
test를 하는 방법에는 여러가지가 있지만 XCTest를 이용하여 Unit Test를 진행하였다.

2021-02-16 06:31 UTC, godrm commented on PokerGameApp/CardViewController.swift
> +    static let padding : CGFloat = (CGFloat(cardCount)-1) // 카드의 간격의 갯수 (7개의 카드이므로 간격은 6번존재)
참고로 이런 상수들은 이런 식으로 표현하는 것도 괜찮습니다.
enum 타입은 init이 없어서 인스턴스를 생성하지 않고 상수들을 묶기에 적합합니다. 참고하세요.
```
enum Constant {
    static let cardCount : Int = 7
}
```

2021-02-16 06:32 UTC, godrm commented on PokerGameApp/CardViewController.swift
>      }()
빌드 패턴이라고 부르기도 하는 데 초기화 이외에 설정하는 값이 없다면 
`let cardImage : UIImage = UIImage(named: "cardback.png") ?? UIImage()` 와 동일합니다. 참고하세요.

2021-02-16 06:33 UTC, godrm commented on PokerGameAppTests/CardDeckTest.swift
> +    }
테스트 코드를 직접 작성한 부분은 좋습니다 :)

2021-02-16 06:33 UTC, merged