Pokergame Step4
code-squad/swift-pokergameapp pull request #147
Opened 2021-02-17 04:39 UTC by lenaios

[주요 작업 내용]
- struct와 class 내부의 내부 속성은 private으로 지정했습니다.
- PokerGame class가 cardDeck과 players의 정보를 갖고 있으며, 카드를 딜링하고 플레이어의 handCard를 리셋할 수 있도록 설계했습니다.
- 기존에는 Dealer와 Player 객체를 별도로 선언했으나, 내부 속성과 기능이 중복되어 Player 객체에 PlayerType으로 구분할 수 있도록 변경했습니다.
- 간단한 데이터 확인을 위해 viewDidLoad 안에 테스트용 코드를 작성했습니다.

+) 커밋 메시지에 `add PokerGame struct`로 잘못 적은걸 깨닫고, cherry-pick으로 해당 커밋으로 돌아가 커밋 메시지를 `add PokerGame class`로 수정해봤습니다.😥

2021-02-17 05:51 UTC, godrm requested changes
수고하셨습니다. PR 열어놓겠습니다.
피드백 내용중에 Players 타입을 선언하는 부분만이라도 꼭 개선해보고 넘어가겠습니다. 
모두 수정하고나서 댓글 남겨주세요.

2021-02-17 05:51 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    init(rule: Rule = .sevenCardStud, players: [Player]) {
Rule 타입처럼 players 대신에 참가 인원수를 지정하는 타입을 만드는 건 어떨까요? 
어차피 내부에 [Player] 배열이 있으니 인원수만 전달해주면 맞춰서 생성할 수 있지 않을까요?

2021-02-17 05:51 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +class Player {
Game 과 Player는 서로 다른 객체니까 다른 파일에 분리해보세요.

2021-02-17 05:51 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +                    player.receive(card: card)
여기 함수가 5단계로 깊어졌네요. 3단계 이상 깊어지면 조금 이상한가 고민해보면 좋겠습니다.

2021-02-17 05:51 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        return handCard
내부 속성을 결국 그대로 [Card] 배열로 전달해주는 이렇게 속성을 전달하지 않는 방법을 고민해보세요.

2021-02-17 05:51 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            }
이렇게 특정한 객체 속성을 가지고 분기처리하는 방식이 전형적인 추상 데이터 타입입니다. 
CS10 OOP에서 제가 다형성을 언급했던 부분을 고려해서 개선해보세요.

2021-02-17 05:51 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    private var players: [Player] = []
여기서 [Player] 배열을 별도로 갖고 있는 마치 [Card] 배열을 가지는 CardDeck 같은 Players 타입을 만들어보세요.
그러면 코드 배치가 좀 달라질 겁니다. PokerGame 이 상위 모듈(타입)가 되고, Players 가 하위 모듈(타입)이 되는거죠.
배열을 직접 속성으로 갖고 있으면 PokerGame에 배열에 추가하거나, 비교하거나, 탐색하는 코드가 반복적으로 생깁니다.
하지만 하위 모듈을 선언하면 상위 모듈은 players.xxx() 형태로 더 단순해질 겁니다.

2021-02-17 15:34 UTC, lenaios commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    private var players: [Player] = []
다음 내용을 보완해서 Push 했습니다 :)
- Players, HandCard 타입 추가로 모듈화
- 카드 딜링 함수의 뎁스를 줄이기 위해 2개의 function으로 분리
- HandCard 정보를 출력하기 위해 `description` 연산 프로퍼티를 정의

2021-02-17 15:34 UTC, lenaios commented
다음 내용을 보완해서 Push 했습니다 :)
- Players, HandCard 타입 추가로 모듈화
- 카드 딜링 함수의 뎁스를 줄이기 위해 2개의 function으로 분리
- HandCard 정보를 출력하기 위해 `description` 연산 프로퍼티를 정의

2021-02-18 05:29 UTC, godrm commented on PokerGameApp/PokerGameApp/Player.swift
> +                print("카드가 부족해 게임을 종료합니다.")
출력 부분은 여기서 처리하지 않고 정상 흐름과 구분할 수 있도록만 하면 더 좋습니다. 
handout()을 return 할 것인지 throw 할 것인지 완료후 completion 클로저를 호출할 것인지 다양한 방법을 고민해보세요.

2021-02-18 05:30 UTC, godrm commented on PokerGameApp/PokerGameApp/Player.swift
> +        (1...rule.rawValue).forEach { _ in
PokerGame.Rule 타입을 썼으면 여기 반복분도 PokerGame.Rule에서 처리할 수 있을까요?

2021-02-18 05:30 UTC, godrm commented on PokerGameApp/PokerGameApp/Player.swift
> +class HandCard {
여기 HandCard, Player, Players 도 별도 파일로 분리해보세요.

2021-02-18 05:30 UTC, merged

2021-02-18 07:15 UTC, lenaios commented on PokerGameApp/PokerGameApp/Player.swift
> +        (1...rule.rawValue).forEach { _ in
PokerGame.Rule 안에 function 을 정의하는 것으로 이해하고 있습니다! 다음 스텝에 반영해서 푸시하겠습니다 :-)