Step 4
code-squad/swift-pokergameapp pull request #161
Opened 2021-02-17 09:04 UTC by zeke-iOS

## 시도

- Players와 Dealer 클래스를 만들고 카드덱을 참조하기 위해 각각 PokerGame클래스를 상속받았었는데 뭔가 부자연스러운 흐름같아 Players와 Dealer 클래스를 PokerGame클래스 안으로 옮겨 nested type으로 구현하였다.
- FiveCardStud클래스와 SevenCardStud클래스를 각각 만들어 PokerGame클래스를 상속받게 하였다.

## 고민

- PokerGame 클래스를 만들고 FiveCardStud와 SevenCardStud를 생성하여 PokerGame을 상속받았는데 포커게임의 두 종류라면 PokerGame 안에 nested type으로 만드는게 더 흐름상 보기 좋지 않을까? 라고 고민하였다.

- 이니셜라이저를 생성할 때 init메소드를 생성하여 초기화해주는것 (아래 예시),

  ```swift
  init(cardDeck: CardDeck = CardDeck(cards: []), players: [Player] = []) {
          self.cardDeck = cardDeck
          self.players = players
      }
  ```

  그리고 초깃값을 지정해주는것 (아래 예시)

  ```swift
  var cardDeck: CardDeck = CardDeck(cards: [])
  var players: [Player] = []
  ```

  이 둘의 차이점에 대해 그리고 어떤 방식으로 사용해야하는지에 대해 고민하였다.

2021-02-17 09:40 UTC, godrm requested changes
수고하셨습니다. 다음 피드백을 확인해서 개선하고 다시 PUSH해보세요.
설명이 부족한 부분은 항목별로 다시 질문하셔도 좋습니다.
전체 수정을 완료하고 나서도 꼭 댓글을 남겨주세요.

2021-02-17 09:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +//        test()
사용하지 않는 함수는 주석으로 남겨놓지 말고 과감하게 지우세요.

2021-02-17 09:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +        print(card)
이 함수만 drawingCardRandomly()에 -ing가 붙어있네요. 다른 함수와 특별히 구분되는 이유가 있나요?

2021-02-17 09:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/FiveCardStud.swift
> +        players.append(per3)
FiveCardStud를 PokerGame을 상속해서 다형성으로 구현한 시도는 좋습니다.
다만 이렇게 하고 Player를 추가하거나 아래 startGame도 카드 개수를 하드코딩한 부분은 아쉽습니다. 
반복문에 들어가는 범위만 지정할 수 있으면 이렇게 구현하지 않아도 될 것 같습니다.

2021-02-17 09:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PokerGame.swift
> +    var dealer: Dealer = Dealer()
내부 속성은 항상 private var를 우선적으로 고려하세요.

2021-02-17 09:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PokerGame.swift
> +        self.players = players
생성할 때 외부에서 값을 전달하는 시도는 매우 좋습니다.

2021-02-17 09:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PokerGame.swift
> +    }
Player 와 Dealer 가 동일한 거 같은데요? 기능이 전혀 필요없는건가요? 구현이 안된건가요? 빈 함수도 보이네요.

2021-02-17 09:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/SevenCardStud.swift
> +class SevenCardStud: PokerGame {
FiveCardStud 와 SevenCardStud는 Rank 나 Suit 처럼 하위 타입으로 하고
PokerGame을 상속받은 경우는 Game을 다양한 게임을 구현할 때 나누면 어떨까요?

2021-02-17 13:26 UTC, zeke-iOS commented on PokerGameApp/PokerGameApp/Model/PokerGame.swift
> +    }
실제 딜러가 하는 기능들은 뭐가 있을까 생각하고 새로운 기능을 추가 할 필요가 있다고 느끼게 되었습니다.
빈 함수는 상속받은 클래스들에서 사용하려고 작성하였지만 빈 함수만 작성해두는것이 불필요하다 느껴 삭제하려고 합니다.😀

2021-02-17 13:40 UTC, zeke-iOS commented on PokerGameApp/PokerGameApp/Model/SevenCardStud.swift
> +class SevenCardStud: PokerGame {
PokerGame클래스 안에 Player, Dealer, SevenCardStud, FiveCardStud 클래스들이 하위 타입으로 들어가게끔 구현하려고 하는데 문제없을까요??

2021-02-17 13:58 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/SevenCardStud.swift
> +class SevenCardStud: PokerGame {
설계는 구현을 통해서 증명해보는 겁니다. 그래도 기존보다 좋은 방향같네요.

2021-02-18 14:10 UTC, zeke-iOS commented
## 과정

- 기존 하위타입으로 구현하기 보다 여러 타입으로 나누고 서로 메소드를 통해 데이터를 주고받으며 기능을 구현하려 전면 수정 하였습니다.
- 크게 PokerGame, Player, Players, Dealer, Card, CardDeck 클래스로 구현하였습니다.



1. PokerGame
   - PokerGame 클래스에는 players와 dealer 객체가 존재합니다. 그리고 startGame()메소드를 통해 포커와 플레이어들에게 각각 카드가 나눠집니다. printParticipantCards() 메소드를 통해 플레이어들과 딜러가 가진 카드들을 출력합니다.



2. Dealer
   - 카드덱을 딜러가 갖고있는게 자연스럽다고 생각하여 cardDeck을 변수로 가지고 딜러가 가질 cards, 그리고 게임타입(stud)인 gameType을 변수로 가지고 있습니다.
   - deal()메소드를 통해 딜러를 포함하여 플레이어들에게 각각 카드를 나눠 가집니다.
   - give()메소드는 딜러가 카드를 나누어줍니다. 반환값으로 5장 혹은 7장의 카드들 입니다.
   - printDealerCards는 딜러가 가진 카드를 출력합니다.
   - readyToStart()는 카드덱을 카드로 채우고 셔플을 하여 게임을 준비하는 메소드입니다.



3. Players
   - player들을 가진 배열 players를 속성으로 가집니다.
   - distribute()메소드는 플레이어들에게만(딜러 제외) 카드를 분배합니다. Players에서 distribute()라는 분배기능을 하는 메소드를 구현하는게 부자연스럽다고 생각하였습니다.
   - printPlayerCards()는 플레이어들이 가진 카드들을 출력하는 메소드입니다.

4. Player
   - cards 변수를 가져 각 플레이어들이 가지는 카드들을 나타냅니다.
   - takeCard()메소드를 통해 카드를 딜러로부터 받습니다.
   - description은 연산프로퍼티로 플레이어의 카드를 출력할 때 사용됩니다.



## 고민

이틀동안 step-4를 2번 갈아엎은것 같습니다. 객체들간의 메시지를 주고받는 것. 그리고 struct와 class에서 값과 참조의 차이점 등을 생각하며 이것들을 코드로 구현하는게 너무나 어려웠습니다. 지나치게 반복되는 수정탓에 커밋도 잊어버려 어느순간부터는 그냥 코딩을 하게되었습니다. ㅠㅠ

2021-02-18 14:40 UTC, godrm commented
수고하셨습니다. Dealer와 Player가 서로 공통점이 있는데 일반화 되지 않은게 아쉽습니다. 
다음 단계에서도 개선해보세요.
주말에 브랜치를 바꿔가면서 여러 버전으로 만들어보는 것도 좋습니다.

2021-02-18 14:40 UTC, merged