Step4 포커딜러와 게임테스트
code-squad/swift-pokergameapp pull request #163
Opened 2021-02-17 12:32 UTC by youngminshim-de

1. Dealer 클래스 생성
2. Participant 클래스 생성
Dealer 와 참가자 모두 카드를 받는 receiveCard() 함수 구현
받은 카드 모두를 return 해주는 getCard() 함수 구현
3.  PockerGame 클래스 생성
CardDeck, Participant의 배열, Dealer, 카드수, 참가자 수를 프로퍼티로 갖는다.
카드를 나눠주는 distributeCard 함수 구현

세 클래스 공통적으로 CustomStringConvertible 프로토콜 채택
Dealer 와 Participant 는 카드의 배열을 String 형태로 return
PockerGame 에서는 출력형태에 맞게 String 형태로 return

2021-02-17 14:05 UTC, godrm requested changes
수고하셨습니다. 다음 피드백을 확인해서 Participants 타입을 만들어보세요. 
PR 오픈해놓을테니 수정하고 PUSH하고 나면 댓글을 남겨주세요.

2021-02-17 14:05 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +        return str
Dealer처럼 데이터를 다루는 객체에서 description을 제공하는 것은 긍정적이지만, 
출력 메시지를 직접 만드는 것은 별로입니다. 이 메소드는 앱에서 딜러 카드를 보여줄 때 도움이 되지 않으니까요.
처리 이후에 출력을 담당하는 곳을 분리해서 별도로 만드는 게 좋습니다.

2021-02-17 14:05 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +    }
내부에 배열만 있네요. 딜러가 카드덱에서 카드를 나눠주지 않던가요?

2021-02-17 14:05 UTC, godrm commented on PokerGameApp/PokerGameApp/Participant.swift
> +    }
딜러와 구현이 거의 동일한 것 같습니다. 공통 요소를 일반화시켜보세요. 어떤 방법이 있을까요?

2021-02-17 14:05 UTC, godrm commented on PokerGameApp/PokerGameApp/PockerGame.swift
> +                    print("카드가 다 소모되었습니다.\n 게임을 종료합니다.")
게임에서도 흐름을 확인해서 distributeCard를 호출한 상위 모듈로 알려주면 상위 모듈에서 출력을 하는 구조가 좋습니다.
그래야 앱을 만들 때 화면에 출력할 수 있습니다. 이렇게 핵심 로직을 구현하는 타입들은 print를 직접 호출하지 않는 게 좋습니다.

2021-02-17 14:05 UTC, godrm commented on PokerGameApp/PokerGameApp/PockerGame.swift
> +    private var numOfParticipant: Int
numOfParticipant는 participants.count 와 같은 값 아닐까요? 계속 속성으로 필요한가요?

2021-02-17 14:05 UTC, godrm commented on PokerGameApp/PokerGameApp/PockerGame.swift
> +    private var participants: [Participant] = []
[Participant] 배열을 직접 다루지 말고 Participants 타입을 선언해보세요.
마치 CardDeck 처럼 [Card]를 가지는 타입을 선언하면 됩니다. 
대신 배열에 접근하도록 하는게 아니라, 여기 PokerGame에서 participants 배열에 접근하는 코드들을 Participants로 옮겨보세요.
그러면 PokerGame 코드가 조금 더 단순해질 겁니다.

2021-02-18 07:04 UTC, youngminshim-de commented
코멘트 내용을 수정해서 다시 push 했습니다.
여기서 궁금한 점은 구현한 내용이 맞는지 확인하기 위해 print()를 어쩔수 없이 사용했는데..
print() 함수는 별 필요가 없다고 하셔서요
그렇다면 구현한 코드가 아웃풋이 제대로 나오는지 보통 어떻게 테스트를 하나요??

2021-02-18 07:10 UTC, godrm commented
> 코멘트 내용을 수정해서 다시 push 했습니다.
> 여기서 궁금한 점은 구현한 내용이 맞는지 확인하기 위해 print()를 어쩔수 없이 사용했는데..
> print() 함수는 별 필요가 없다고 하셔서요
> 그렇다면 구현한 코드가 아웃풋이 제대로 나오는지 보통 어떻게 테스트를 하나요??

단위 테스트를 합니다. 꼭 출력해서 눈으로 확인하는 게 테스트가 아닙니다. 다음주부터는 단위 테스트에 대해서 언급할 예정입니다.
print() 해서 출력하는 경우는 이제 없을꺼에요.

2021-02-18 07:12 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +                }
Int 타입이 아니라 numOfCard를 표현할 타입이 있으면 더 좋겠습니다. 
다음 단계를 하면서 개선해보세요.

2021-02-18 07:13 UTC, godrm commented on PokerGameApp/PokerGameApp/Participants.swift
> +    init(numOfParticipant: Int) {
스위프트 함수 이름은 괄호 앞부분 + 매개변수까지라고 생각하세요.
init(number ofParticipant:) 혹은 init(with numbers:) 이런 식으로도 표현하기도 합니다.

2021-02-18 07:14 UTC, merged