pokergameapp step3 - 포커 딜러와 게임 테스트
code-squad/swift-pokergameapp pull request #164
Opened 2021-02-17 14:00 UTC by 1song2

* step3 PR에서 피드백 주신 내용을 반영해 코드를 수정하였습니다.
* `Player`와 `Dealer` class를 만들었습니다. 포커룰을 잘 몰랐는데 찾아보니 dealer는 dealing의 역할 + 게임에 참여하는 플레이어라는 것을 알게 되어 `Player`의 subclass로 `Dealer`를 정의하였습니다.
* `PokerGame` class를 만들고, 게임 참여 인원 관련 `GameRule` enum과 게임 종류인 `StudPoker`를 Nested enum으로 구현했습니다. 
* 참여 인원 미달 혹은 초과일 경우 error를 발생시키고 처리할 수 있도록 `PokerGame` class의 initializer에 throws 키워드를 더해주었습니다. 그동안 에러 처리라 하면 아주 어려울 것이라 생각해 시도할 엄두를 못냈었는데 Language guide에 내용이 자세하게 아주 잘 나와있어 찬찬히 따라하니 생각만큼 어렵진 않았던 것 같습니다!
  * error condition들을 모아놓은 `PokerGameError` enum이 4줄로 아주 짧아 독립된 파일로 나눠주기가 뭐해 `PokerGame` class 아래 두었는데, 이런 경우도 독립된 파일에 작성하는 것이 좋은 습관인지 궁금했습니다.
* 콘솔 스크린샷
  <img width="306" alt="Screen Shot 2021-02-17 at 10 36 27 PM" src="https://user-images.githubusercontent.com/56751259/108214580-aa767600-7173-11eb-9ac0-9e55d3688b0b.png">

2021-02-17 14:45 UTC, godrm requested changes
수고하셨습니다. 다음 피드백을 확인해보고 Players 타입을 선언해보세요.
PR 오픈해놓겠습니다.

2021-02-17 14:45 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +    var cardDeck: CardDeck
내부 속성을 표현할 때는 private var를 우선적으로 고려하세요.

2021-02-17 14:45 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +        cardDeck = CardDeck()
이렇게 내부에서 필요한 데이터 혹은 타입을 의존한다고 합니다.
init()할 때 외부(상위 모듈)에서 의존하는 데이터를 매개변수로 전달해주는 게 좋습니다. 
참고하세요.

2021-02-17 14:45 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +                return 7
enum 타입을 만든 것은 좋은데, 다시 Int 값으로 가져오는 것은 별로입니다. 
이 부분은 내일 수업때 언급할 예정입니다. 
타입을 선언하면 내부 속성을 값을 가져오려고 하기 보다는 타입에게 일을 시킬 수 있는 게 좋습니다.

2021-02-17 14:45 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    private let players: [Player]
여기 [Player] 배열을 포함하는 Players 타입을 선언해보세요.
CardDeck이 [Card] 배열을 포함하는 것처럼 players 속성에 접근하는 코드들을 Players 내부로 옮길 수 있을 겁니다.

2021-02-17 14:45 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        return "🃏카드게임 종류: \(gameType), 👨‍👩‍👧‍👦참가자: \(players.count)명\n\(playersResult)\n\(dealerResult)"
description을 제공하는 것은 좋지만, 
모든 결과를 출력하기 위해서 문자열을 만드는 것은 좋지 않습니다.
우리는 결국 앱을 만들어서 화면에 표시해야 하는데, 여기서 만드는 문자열은 모두 필요가 없어집니다.
game 자체를 넘겨서 출력하는 방법을 고민해보는 게 좋습니다. 이 부분은 당장 개선할 필요가 없지만 한 번 고민해보세요.

2021-02-17 14:45 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        return players.map { $0.showdown() }
클로저를 이용한 이런 시도는 좋네요.

2021-02-17 14:45 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    case tooManyPlayers(playersNeededToLeave: Int)
에러를 선언했으면 어느 타입과 관련된 것인지 nested 하는 것도 좋습니다.

2021-02-18 10:11 UTC, 1song2 commented on PokerGameApp/PokerGameApp/Dealer.swift
> +    var cardDeck: CardDeck
이전에는 외부 클래스에서 가져다 쓰는 경우가 있어 private으로 정의해주지 못했었는데, 전체적으로 구조를 재설계하면서 수정했습니다!

2021-02-18 10:13 UTC, 1song2 commented on PokerGameApp/PokerGameApp/Dealer.swift
> +        cardDeck = CardDeck()
상속 때문에 `init()`을 override하면 매개변수를 넣을 수 없다고 착각했던 것 같습니다. override keyword를 제거하고 매개변수를 통해 전달하도록 수정했습니다.

2021-02-18 10:18 UTC, 1song2 commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +                return 7
수업 내용을 참고하여 타입이 일을 하도록 수정해보았는데, 수업에서 보여주신 내용처럼 깔끔하게 구현하지는 못했습니다🥲 그래도 이러저리 수정해보면서 타입에게 일을 시킨다는 표현을 조금이나마 이해하게 된 것 같습니다.

2021-02-18 10:29 UTC, 1song2 commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    private let players: [Player]
CardDeck처럼 Players 타입을 선언하는 것도 그렇게 어렵지 않을거라 생각했는데 착각이었습니다... 전체적인 구조를 고치느라 생각보다 시간이 오래 걸렸네요🙏

* 수정 전: Dealer 클래스의 `deal()` 함수가 플레이어의 내부 프로퍼티에 접근해 카드를 더해주는 역할까지 수행
* 수정 후
  * Dealer 클래스의 `deal()` 함수는 dealer가 덱에서 카드를 하나 뽑아 리턴하는 것까지 역할
  * Player와 Players 클래스에 `dealt()` 함수를 추가해 매개변수로 카드를 받아 내부 프로퍼티 cards에 추가할 수 있도록 함

2021-02-18 10:35 UTC, 1song2 commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        return "🃏카드게임 종류: \(gameType), 👨‍👩‍👧‍👦참가자: \(players.count)명\n\(playersResult)\n\(dealerResult)"
말씀하신대로 문자열은 물론이고 따로 구현했던 에러 처리도 앱에서는 쓰일 일이 없더라구요. (인원을 직접 숫자로 입력하는 방식이 아니라 제한된 선택지 중에서 선택하는 방식이기 때문에..) 중간 단계도 최종 결과물을 염두해두고 진행해야겠다는 생각을 하게 되었습니다!

2021-02-18 10:35 UTC, 1song2 commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    case tooManyPlayers(playersNeededToLeave: Int)
관련된 타입인 PokerGame 안으로 넣어주었습니다!

2021-02-18 10:36 UTC, godrm commented
수고하셨습니다.

2021-02-18 10:36 UTC, merged