Step 4 구현, Step 3 피드백 반영
code-squad/swift-pokergameapp pull request #180
Opened 2021-02-19 08:46 UTC by dahun-lee-daji

- step 4 및 피드백 반영 완료하여 PR 보내드립니다!

반성 : 
- 요구사항에 맞는 pokergame을 정신없이 구현하다보니, method를 일단 만들기만 해서 구현한 느낌입니다...
- 정신없음에 따라서 커밋을 분배하지 못하고 거대해졌습니다..

고민 할 점 : 
- 상속 시 private한 프로퍼티는 접근 할 수 없는데, 이로 인해 접근하기 위한 method를 만들어 주어야 하는데, 이게 옳은 방법인지 고민 중 입니다.
- Deck을 각 player, dealer의 핸드로 재사용했는데, Hand를 새로 만들었어야 할 지 고민했지만, 큰 의미가 없을거라 생각하여 Deck을 사용했습니다. 하지만 이렇게 될 경우 읽는 사람의 혼란을 초래 할 수 있다고 생각합니다.

2021-02-19 08:53 UTC, dahun-lee-daji commented
질문사항 : 
이전 feedback에 error를 nested를 사용해서 error가 발생하는 class내부에 넣어주는게 좋다고 하셨습니다. 
그런데 nested와 관련된 키워드를 탐색해 보았으나, 적합한 정보를 찾지 못했습니다. 추가적인 키워드를 주실 수 있을까요?

2021-02-19 09:10 UTC, godrm requested changes
다음 피드백을 확인해보세요. 
nested는 수업 시간에도 언급했었습니다. https://docs.swift.org/swift-book/LanguageGuide/NestedTypes.html 읽어보세요.
PR 열어놓을테니 print 하는 로직들 흐름만 개선해서 PUSH해주세요.

2021-02-19 09:10 UTC, godrm commented on PokerGameApp/PokerGameApp/model/Dealer.swift
> +        print("딜러 [\(showHandAsString())]")
우리가 구현하는 로직에 print를 호출하는 부분이 있으면 이상한 겁니다. 리턴 타입을 활용해서 데이터를 전달해주려고 노력해보세요.

2021-02-19 09:10 UTC, godrm commented on PokerGameApp/PokerGameApp/model/Dealer.swift
> +            print("카드가 부족하여 종료합니다.")
예외 상황이 되면 print 하는게 목적이 아니라 흐름을 제어하는 게 목적입니다. 
sendCard()를 호출한 상위 모듈에서는 정상적으로 나눠줬는지, 실패했는지 알수가 없게 됩니다.
리턴하거나 rethrow해서 상황을 알려주고, 재시도할 지, Alert를 표시할 지 상위에서 판단할 수 있도록 구현하는 게 좋습니다.
print는 데이터 흐름에서 마지막 단계를 처리하는 타입에서만 하면 됩니다.

2021-02-19 09:10 UTC, godrm commented on PokerGameApp/PokerGameApp/model/Deck.swift
> +        print("")
마찬가지로 출력하는 로직을 포함하지 마세요.

2021-02-19 09:10 UTC, godrm commented on PokerGameApp/PokerGameApp/model/Deck.swift
> +        return strArray
모든 카드를 다 전달하는 메소드가 있으면 내부 속성을 감추고 복잡성을 감추는 의미가 퇴색됩니다.
저 값들을 모두 주는 건 메모리 복사가 일어나기 때문에도 좋은게 아닙니다. 
다른 방법으로는 클로저를 매개변수로 전달해서 내부의 값을 가지고 동작하도록 하는 방법도 있습니다. 참고하세요.

2021-02-19 09:10 UTC, godrm commented on PokerGameApp/PokerGameApp/model/Players.swift
> +        }
print 하는 로직을 내부에 두지 말고 외부에서 print 하는 closure를 매개변수로 전달하도록 개선해보세요.

2021-02-19 09:10 UTC, godrm commented on PokerGameApp/PokerGameApp/model/PokerGame.swift
> +        self.players.resetSelf()
game에서 출력을 위한 객체로 데이터를 전달하는 흐름이 좋습니다.
왜냐하면 앱을 만들때는 UIView 객체가 따로 있을꺼라서 거기서 출력을 해야 합니다.
그 구조를 그대로 활용할 수 있도록 하는게 좋습니다.

2021-02-20 09:04 UTC, dahun-lee-daji commented
주말에 PR드려 죄송합니다.😢
피드백 주신, print 관련 로직을 수정했습니다.

2021-02-20 09:04 UTC, dahun-lee-daji commented on PokerGameApp/PokerGameApp/model/PokerGame.swift
> +        self.players.resetSelf()
해당 내용은 step 5 에 추가하여 진행하겠습니다

2021-02-20 09:17 UTC, godrm commented
수고하셨습니다.

2021-02-20 09:17 UTC, merged