[Lollo] Step 5 - 포커게임 결과 화면
code-squad/swift-pokergameapp pull request #181
Opened 2021-02-19 09:55 UTC by eeeesong

안녕하세요 JK, Step 5 PR 보냅니다!🙂

### 주요 학습 내용

- **객체 수정** 

  - 수업 내용을 참고하여 `Participants` class를 새로 생성하였습니다. 해당 클래스가 뷰 업데이트에 필요한 정보를 모두 가지게 되어, 정보 업데이트가 수월해졌습니다. 

  - `Participants` -> `InfoBoard` -> `ViewController`로 데이터를 넘기되, 모든 프로퍼티는 private으로 설정하고 메소드를 통해 전달하도록 했습니다.

  - 앱 화면을 통해 게임 진행 시 게임이 끝나면 안되기 때문에, 만약 카드의 수가 부족할 경우 Dealer가 덱을 리셋하도록 바꿨습니다. 

    ((🙋‍♀️ **질문이 있습니다**)) 이 과정에서 기존에 있던 옵셔널 리턴을 전부 지우고, removeOne 메소드 수행 시에도 강제 언래핑을 사용하도록 바꿨습니다. 이전 과정에서 nil이 되지 않음을 확인하기 때문에 !를 사용했는데 혹시 이런 경우에도 ! 사용은 좋지 않을까요?

- **View에 게임 화면 구현**

  - `segmentedControl` 작동 방식에 대해 학습하고 구현했습니다. 
  - Step 1에서 작성한 addCards 메소드를 활용하여, 게임 룰에 맞게 뷰에 카드 및 플레이어 라벨을 추가했습니다.
  - 기존에 작성한 메소드가 `stackView`를 통한 것이 아니어서 많은 한계가 있다고 느꼈습니다. 하지만 당장 stackView, autoLayout 등을 학습해서 구현하기에는 벅차서 우선은 매우 미흡하지만 frame을 활용하는 방식을 유지했습니다.🥲 차차 학습해보도록 하겠습니다...

- **해상도 처리**: 1x, 2x, 3x의 의미를 파악하고, 주어진 이미지를 [appicon.co](https://appicon.co/#image-sets) 를 통해 1x,2x,3x에 각각 대응할 수 있도록 변환하여 추가하였습니다.

- **Shake Event**: `motionEnded`를 override하여 이벤트 발생시키기, 시뮬레이터에서 shake event를 발생시키는 방법 등을 학습하였습니다.

2021-02-19 10:40 UTC, godrm requested changes
수고하셨습니다. 
뷰컨트롤러에서 클로저를 이용해서 뷰를 생성하는 방법을 적용해보세요.

2021-02-19 10:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +        case diamond = "d"
기존 요구사항을 유지하면서 새로운 기능을 구현하도록 하는게 좋습니다.

2021-02-19 10:40 UTC, godrm commented on PokerGameApp/PokerGameApp/InfoBoard.swift
> +    private var cardStackList: [[Card]]
여기있는 데이터는 어딘가 다른 객체에도 있는 데이터 아닌가요?
단지 출력을 위한 데이터 구조인가요?  어떻게 사용하는지도 보고 다시 의견을 남길게요.

2021-02-19 10:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Participant.swift
> +        case dealer, player
Role을 타입으로 dealer, player로 나누면 다형성으로 구현하는 게 아니라
어딘가에서 role을 비교해서 분기처리를 하게 됩니다. 
각각 세부 타입에서 값을 갖고 있고, 지정하는 방법이 좋습니다.

2021-02-19 10:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Participant.swift
>          return ""
이 메소드는 왜 필요한지 모르겠네요.

2021-02-19 10:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Participant.swift
> +            cards.append(cardDeck.removeOne()!)
네. 이렇게 쓰면 안됩니다. removeOne() 호출하고 없으면 여기서 크래시가 발행해서 멈춰버립니다. 
안전하게 처리하셔야 합니다.

2021-02-19 10:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Participants.swift
> +        list = players
혹시 player를 다 전달받지 않고 여기서 생성해도 되지 않나요?

2021-02-19 10:40 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        updateView(with: players, stacks)
game.info()를 가져오는 게 아니라 game에 closure를 넘겨서 cardView를 만드는 방법도 있습니다. 
game 내부 속성이나 players, card stack 을 몰라도 클로저로 선언한 로직을 전달하는 방법을 도전해보세요.

2021-02-19 13:12 UTC, eeeesong commented on PokerGameApp/PokerGameApp/InfoBoard.swift
> +    private var cardStackList: [[Card]]
아 넵 맞습니다
participants가 전부 가지고 있습니다!
중복 개선해보겠습니다

2021-02-19 13:12 UTC, eeeesong commented on PokerGameApp/PokerGameApp/Participants.swift
> +        list = players
넵 가능할 것 같습니다! 개선해보겠습니다

2021-02-19 13:13 UTC, eeeesong commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        updateView(with: players, stacks)
아직 전혀 감이 오지 않는데 클로저 공부를 좀 더 해보고 방법을 연구해보겠습니다!
피드백 감사드립니다

2021-02-19 13:16 UTC, eeeesong commented on PokerGameApp/PokerGameApp/Participant.swift
>          return ""
하위 클래스에서 오버라이드하여 정의하기 위해 선언해준 것입니다!
혹시 myName() 자체가 왜 있는 건지 말씀하신 걸까요??

2021-02-19 13:24 UTC, godrm commented on PokerGameApp/PokerGameApp/Participant.swift
>          return ""
아.. 상위 메소드라서 아무 기능이 없다는 거군요. 
오해할 수 있기도 해서 이렇게 구현하는 게 썩 좋은 게 아닙니다. 나중에 프로토콜로 추상화하는 방법을 학습해보세요.

2021-02-22 08:29 UTC, eeeesong commented
안녕하세요 JK, 프로토콜 및 클로저에 대해 학습한 뒤 Step 5를 수정했습니다.

아직 부분적으로만 적용을 할 수 있었는데요, 다음 미션을 진행하면서 더 학습을 한 뒤 심도 깊게 활용할 수 있도록 시도해보겠습니다🙂



이번 수정 내용은 아래와 같습니다!



1. Participant `프로토콜` 생성: Dealer/Player의 기능을 추상화한 Participant 프로토콜을 만들고, 기존의 superclass 상속 관계를 없앴습니다.
   - 코드 양은 전보다 좀 많아졌지만, 상위 클래스의 의미없는 빈 메소드가 사라지고 프로토콜을 통해 기능을 요약적으로 볼 수 있어서 읽기엔 더 편해졌다고 느꼈습니다. 
2. `클로저`를 통한 View 생성: ViewController로 필요한 데이터를 받아오는 대신, game에 클로저를 넘겨서 View를 만들 수 있도록 변경하였습니다.
3. 기타 피드백 반영:
   - Participants와 기능이 겹치는 InfoBoard 클래스를 삭제했습니다. 
   - 강제 언래핑을 없애고 옵셔널바인딩 방식을 개선했습니다.

2021-02-22 08:40 UTC, godrm commented on PokerGameApp/PokerGameApp/Participant.swift
> +    var cards: [Card] { get }
앞으로 이야기 하겠지만 속성을 가져갈 수 있도록 프로토콜에 get을 만드는 것도 조심할 필요는 있습니다.
아래처럼 메소드 자체를 선언하는 게 더 좋습니다.

2021-02-22 08:42 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +        }
딱 한 번만 카드를 나눠준다면 적당하네요.
만약 52장 카드 중에서 5stud를 3명이 한다면 15장씩 나눠주니까, 3판정도는 진행할 수 있습니다. 
여러번 할 때도 도움이 될까요?
혹은 한 명이 한장씩 나눠갖는 단계를 둬야 한다면 어떨까요? 
요구사항이 바뀔만한 부분은 고려해서 메소드를 작성하는 것도 좋습니다.

2021-02-22 08:43 UTC, godrm commented
수고하셨습니다. 수퍼 클래스로 추상화할지, 프로토콜로 추상화할지 연습을 해보세요. 장단점이 있습니다.

2021-02-22 08:43 UTC, merged