Pokergameapp step5
code-squad/swift-pokergameapp pull request #189
Opened 2021-02-20 07:45 UTC by ITzombietux

어제 거의 스텝을 진행하지 못해서 지금이라도 PR을 보냅니다. ㅠㅠ

- 타입을 구체화하는 것이 감이 올듯 하면서도 오지 않습니다. ㅠㅠ player를 players로 좀 더 타입을 구체화해서 캡슐화 시키는 것까지는 이해가 되는데 구체화한 타입이 어떤 역할을 해야하는지에 대한 정리가 안되니 역할이 애매해져서 고민이 많았습니다.
- 게임 모드가 계속 변함에 따라 기존 플레이어들과 뷰를 어떻게 바꿔줘야 하는지도 생각보다 힘들었습니다. 결국엔 PokerGame Players를 초기화하는건 PokerGame 클래스에서, 뷰를 초기화하는건 ViewController에서 했는데 이것도 아닌거 같아서 수정하려던 참에 PR을 보냅니다.!

2021-02-20 08:53 UTC, godrm requested changes
주말인데 수고하셨습니다. 
피드백 부분들을 확인해보고 개선해보세요. PR은 오픈해놓을게요.

2021-02-20 08:53 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Card.swift
> +            }
객체가 description을 제공하는 것은 객체 속성 일부를 문자열로 확인하기 위한 겁니다.
이미지 파일과 매칭하기 위해서 내부 선언을 바꾸는 건 그만큼 조심해야 합니다. 
아래 Card.description에서도 suit.rawValue에 접근하는 게 아니라 `\(suit)`로 접근하면 전혀 다른 동작을 하겠죠.
그게 다른 개발자에게는 혼란을 줄 수 있습니다. 
Card를 포함하는 상위 타입을 선언하거나, Card와 이미지를 매칭하는 로직을 구현하는 것도 방법입니다.

2021-02-20 08:53 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Card.swift
>      let rank: Rank
(아래쪽이 diff가 안 잡혀서 표시가 안되는데)
description 내부에서도 suit.rawValue 나 rank.description을 쓰는게 아니라 그냥 \(suit)\(rank) 형태로 하면 description이 참조가 됩니다. 객체를 문자열로 표현할 때 알아서 찾아지는 용도 정도입니다. 
CustomStringConvertible에서 전달하는 문자열에 의존하는 로직을 구현하지 마세요.

2021-02-20 08:53 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
>          return self.name
수업시간에도 말했는데 private 으로 바꾸고 나서 get- show- 이렇게 값을 가져가는 메소드를 추가하지 마세요.
대신 Dealer.getHandInfo()를 호출하는 곳에서 무엇을 하는지 살펴보세요. 
그 로직을 클로저로 전달하는 방법도 있고, 직접 비교하는 방법도 있습니다. 값을 가져가지 않고 처리하는 방법을 찾아보세요. 
다른 브랜치에 있는 코드를 살펴봐도 좋습니다.

2021-02-20 08:53 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Players.swift
> +        players.append(player)
여기 Players 타입 내부에 있는 메소드들도 제가 의도했던 내용이 아닙니다. 
이렇게 작성하면 public var로 속성을 접근하는 것과 같아집니다.
저 값을 가져가서 비교하는 지, 계산하는 지, 탐색하는 지 살펴보고 해당하는 로직을 Players 에서 메소드로 제공하세요.
로직을 모두 처리하기 어려우면, 클로저로 로직을 넘기는 방식을 고려하세요.

2021-02-20 08:53 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/PokerGame.swift
>          static let five = 5
위에 Mode 와 NumberOfCards는 같은 정보를 표현하는 다른 타입이네요? 합쳐서 구현해도 될 것 같은데요?

2021-02-20 08:53 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            startPorkerGame(gameMode: self.mode, NumberOfPlayer: numberOfPlayers)
selectecdSegmentIndex와 NumberOfPlayer 관계를 잘 생각해보세요.
NumberOfPlayer.init()으로 처리할 수 있을 겁니다. 이런 switch-case 구문을 사용할 때마다 줄일 수 있는 방법을 찾아보세요.

2021-02-21 03:03 UTC, ITzombietux commented
피드백 반영 후 Push합니다.!!
- card -> cardImage로 변경하는 부분에서 Hand, Player, Dealer에 UIKit을 import하면 안될거 같은데 달리 방법이 생각이 나질 않아 우선 push후 수정하려고 합니다.

- ViewController segmentedControl에서 switch case도 피드백해주신거 고려해서 여러번 수정을 거쳤는데 원하는 동작이 잘 이루어지지 않아 이 부분도 우선 push후에 꼭 수정해보려고 합니다. ㅠㅠ

2021-02-21 03:19 UTC, godrm commented on PokerGameApp/PokerGameApp/Models/Dealer.swift
> +class Dealer: Playable {
Card, Player, Dealer 처럼 하위 모듈들은 UIKit에 의존하지 않는 게 좋습니다. 
UIKit은 출력을 위한 또 다른 뷰 프레임워크에 불과합니다. 다른 뷰에 출력할 수도 있는거죠. 
그러니까 UIImage를 여기서 처리하지 않는 게 더 좋은 구조입니다. 참고하세요.

2021-02-21 03:20 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        default: break
이런 값도 switch-case 대신 enum 타입을 선언하고 NumberOfPlayer.init() 형태로 표현할 수 있습니다. 
세부적인 타입을 선언하고 분기문을 없애는 게 좋습니다.

2021-02-21 03:20 UTC, godrm commented
수고하셨습니다~

2021-02-21 03:20 UTC, merged