Step5 (JEJE)
code-squad/swift-pokergameapp pull request #190
Opened 2021-02-20 16:10 UTC by JUNGYUN-Daegu

Step5를 구현했습니다.

예전에 UISegmentedControl 구현 시 tintColor만 설정해주면 예시처럼 divider와 boarder에 색을 입힐 수 있었는데 iOS 버전업이 되면서 구현 방법이 바뀐건지 궁금합니다. 인터넷에서 예전 코드를 따라해봤을 때 예상하는 결과와 비슷하게 구현되지 않아서 찾아보니 이와 같은 정보를 봐서요. 아니면 구현 방법을 제가 놓치고 있는 건지 힌트 부탁드립니다 

횡방향 스택뷰를 종방향 스택뷰에 넣으면서 autolayout잡는데 아직 많이 미숙하다는 생각을 하게된 미션이었습니다. 여러가지 문제가 많지만 현재 구현에서 시뮬레이터를 똑바로 세우면 목표 화면에 가깝게 구현되는데 눕히면 레이아웃이 완전 깨지는 현상이 발견되고 있습니다.

ViewController에서 UISegmentedControl로 변수를 입력받다보니 일부 로직을 여기서 구현하게 돼서 객체지향지향적인 코딩에서 약간 벗어나가 있는 것 같아 아쉽습니다. 남는 시간에 개선이 필요한 것 같습니다.

2021-02-20 16:12 UTC, JUNGYUN-Daegu commented on PokerGameApp/PokerGameApp.xcodeproj/project.pbxproj
> +		88EEB4C325DE6A9700D1D840 /* Model */ = {
swift 파일들을 Model, View, Controller 디렉토리에 넣었습니다

2021-02-21 03:31 UTC, godrm requested changes
주말인데도 수고하셨습니다. 다음 피드백을 확인해보시고, 개선해보세요.

2021-02-21 03:31 UTC, godrm commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +    }
NumberOfPlayers 나 StudVariant 는 ViewController보다 Game과 관련이 높은 타입인 것 같아요. 그러니까 Game과 같은 파일에 포함하는 게 좋겠네요.

2021-02-21 03:31 UTC, godrm commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +        let control = UISegmentedControl(items: ["7 cards", "5 cards"])
`["7 cards", "5 cards"]`는 StudVariant과 관련이 높은 값 같네요. 
Rank나 Suit 처럼 CaseIterable 프로토콜을 채택하면 하드코딩하지 않고 배열을 구할 수 있지 않을까요?

2021-02-21 03:31 UTC, godrm commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +        let control = UISegmentedControl(items: ["2명", "3명", "4명"])
`["2명", "3명", "4명"]` 도 마찬가지로 playerNumbers와 관련이 높아보입니다. 하드코딩하지 않고 playerNumbers에서 생성할 수 있을까요?

2021-02-21 03:31 UTC, godrm commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +        generateGameDashBoard(with: gameResult)
gameResult를 가져와서 전달하는 구조도 나쁘지 않습니다만. 값을 가져오지 않고 game에 generateGameDashBoard 내용을 클로저로 전달하는 방법도 있습니다. 그러면 카드 배열을 가져오지 않고, card만으로 뷰를 생성할 수 있습니다. 이 방법을 도전해보세요.

2021-02-21 03:31 UTC, godrm commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +            print("meh")
여기 switch-case 대신에 studVariant = StudVariant.init() 형태로 표현해보세요. 
default에 print 구문은 전혀 의미가 없습니다. 차라리 그냥 비워두세요. ;만 찍어도 됩니다. (switch구문을 빼면 안해도...)

2021-02-21 03:31 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Card.swift
> +        return UIImage(named: cardImageName) ?? nil
가장 하위에 있는 Card 가 UIKit 을 포함하는 것은 좋은 선택이 아닙니다.
UIKit은 출력을 위한 뷰 프레임워크라서 이런 하위 모델과는 분리하는 게 좋습니다. 
이렇게 파일이름을 처리하는 것은 상위 모듈 중에서 처리해야 합니다. 다른 곳으로 옮겨보세요.

2021-02-21 03:31 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Card.swift
> +    }
여기 makeCardImageView 도 마찬가지로 뷰와 관련된 코드라서 분리하세요.

2021-02-21 03:31 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Dealer.swift
> +    }
위에 언급한 것처럼 배열을 전달하지 말고, 매개변수로 클로저를 전달하는 구조로 변경해보세요.

2021-02-21 12:20 UTC, godrm commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +        game.selectStudVariant(index: sender.selectedSegmentIndex)
아.. Int 타입말고 StudVariant.init(), NumberOfPlayers.init() 을 해서 세부 타입을 넘겼으면 좋았을 것 같네요.

2021-02-21 12:22 UTC, godrm commented
주말인데 수고하셨습니다.

2021-02-21 12:22 UTC, merged

2021-02-21 13:30 UTC, JUNGYUN-Daegu commented
JK야말로 주말인데 리뷰 봐주신다고 고생이 많으십니다🙏  아직 수정 완료가 아니라 아쉽네요 ㅠ... 앞으로도 틈틈히 리뷰 해주신거 다 반영하도록 하겠습니다. 감사합니다~

2021-02-21 13:31 UTC, JUNGYUN-Daegu commented on PokerGameApp/PokerGameApp/Controller/ViewController.swift
> +        game.selectStudVariant(index: sender.selectedSegmentIndex)
아하 그렇군요.... 😵 수정하도록 하겠습니다

2021-02-21 13:55 UTC, godrm commented
네. 이제 다음주부터는 저도 천천히 리뷰하려구요 ㅎㅎ 다들 열심히 하길래... 내일 봐요