Cri poker game app step five
code-squad/swift-pokergameapp pull request #192
Opened 2021-02-21 13:03 UTC by panther222128

새로운 브랜치에서 다시 PR 보냅니다. 주말 늦은 시간까지 신경써주셔서 정말 감사합니다.

Players: willJoinGame 배열을 public에서 private으로 변경했습니다. Dealer 클래스에 핸드를 제출하기 위한 함수를 추가했습니다.

Dealer: 카드 배분에서 여분의 카드가 없는 경우와 그렇지 않은 경우를 나눴습니다. 플레이어로부터 핸드를 받는 함수를 추가했습니다.

GameOperator: 게임 진행을 위한 함수를 구현했습니다.

ViewController: 버튼, shake 모션 함수, 게임 진행, 스택 뷰 추가 함수, 이미지 파일이름을 위한 변환기를 구현했습니다.

2021-02-21 14:04 UTC, godrm requested changes
우선 충돌난 파일들부터 해결하시고, 피드백 내용에 있는 사항들을 개선해보세요.
주말에도 고생하셨습니다. 다음주부터는 주말이나 늦은 시간에는 리뷰 안할 겁니다 ㅎㅎ 
이 PR 열어놓고 개선해도 되구요. 이번 프로젝트 미션은 마무리하고 다음 프로젝트를 진행해도 됩니다. 
본인이 선택해보세요. 확인하고 닫도록 하겠습니다.

2021-02-21 14:04 UTC, godrm commented on PokerGameApp/PokerGameApp/CardDeck.swift
>          print("Reset deck")
앞으로는 하위 모듈에서 print를 하거나 요구사항에 임시로 확인해보라는 사항 외에는 print를 안 쓰게 될 겁니다.

2021-02-21 14:04 UTC, godrm commented on PokerGameApp/PokerGameApp/GameOperator.swift
> +>>>>>>> bb7e5f81... 게임 진행을 위한 함수를 구현했습니다.
이런.. 여기 머지 충돌을 해결하지 않았네요. 이 소스는 빌드가 안됩니다 ㅜㅜ

2021-02-21 14:04 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            viewBoardContents[i] = viewBoardContents[i].map({$0[$0.startIndex] == "\u{2661}" ? "h\($0[$0.index(after: $0.startIndex)])" : $0})
이렇게 코드가 반복되고 있다는 것은 접근 방식을 다르게 해서 해결할 수 있을 겁니다.
기능을 분리해보세요.

2021-02-21 14:04 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            restartGame(playersNum: playersNum, cardStud: cardStud)
여기 if-else 구문도 playersNum.init() 이나 cardStud.init() 처럼 세부 파입을 만들어서 처리해보세요.
Card.Rank 나 Card.Suit 과 비슷하게 하면 될 겁니다. 
참가자와 카드스터드에 대한 타입이 없어서 이렇게 처리하게 되는 겁니다.

2021-02-21 14:04 UTC, godrm commented on PokerGameApp/PokerGameApp/Player.swift
> +>>>>>>> 1983ea1b... dealer에 있었던 recruit를 participate로 받았습니다. 이니셜라이저에서 핸드를 제외했습니다.
여기도 충돌 해결부터 하셔야 겠네요.

2021-02-21 14:04 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
>                  cardDeck.removeOne()
Players 타입을 선언했는데도 여기가 여전히 복잡하네요. if, for 구문등을 세부 타입에서 활용할 수 있도록 개선해보세요.
players 내부 배열이나 값을 값을 가져오는 게 아니라, 클로저 형태로 값을 처리할 로직을 전달하도록 개선해보세요.

2021-02-21 14:04 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +    public var hands = [[String]]()
이 타입은 어디서 쓰는지 모르겠어요. 하지만 여전히 배열을 직접 다루는 것 같네요.

2021-02-21 14:25 UTC, panther222128 commented
> 우선 충돌난 파일들부터 해결하시고, 피드백 내용에 있는 사항들을 개선해보세요.
> 주말에도 고생하셨습니다. 다음주부터는 주말이나 늦은 시간에는 리뷰 안할 겁니다 ㅎㅎ
> 이 PR 열어놓고 개선해도 되구요. 이번 프로젝트 미션은 마무리하고 다음 프로젝트를 진행해도 됩니다.
> 본인이 선택해보세요. 확인하고 닫도록 하겠습니다.

말씀 감사합니다. 더 진행해보겠습니다.

2021-02-24 12:01 UTC, panther222128 commented
> 우선 충돌난 파일들부터 해결하시고, 피드백 내용에 있는 사항들을 개선해보세요.
> 주말에도 고생하셨습니다. 다음주부터는 주말이나 늦은 시간에는 리뷰 안할 겁니다 ㅎㅎ
> 이 PR 열어놓고 개선해도 되구요. 이번 프로젝트 미션은 마무리하고 다음 프로젝트를 진행해도 됩니다.
> 본인이 선택해보세요. 확인하고 닫도록 하겠습니다.

다시 PUSH했습니다.

진행하면서 생각한 것은 아래와 같습니다.
1. 수동적인 객체도 존재할 수 있다는 것
2. 클래스를 타입으로 여기고 다룰 수 있다는 것
3. 캡슐화와 전달 (한 객체가 속성은 그대로 가지고 있으면서 다른 객체로부터 수행하라는 명령을 자신 고유의 속성을 다루고 다른 객체에 전달)
4. 지금에서야 깨달은 것 == enum 타입을 사용하지 않았다는 것
5. 주말에 너무 무리하면 월화수가 힘들다는 것....

enum을 타입으로 활용하고 init 하는 등 다루는 것에 대해 학습하고 실제로 활용해봐야 할 것 같습니다.

2021-02-24 14:06 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            restartGame(playerNum: gameOperator.num, cardStud: gameOperator.stud)
아예 if-else 구문을 없앨 수 있습니다. 값들이 바뀌는 게 규칙적네요. 
아니면 Dictionary를 써서라도 enum 타입을 적극 활용해보세요.

2021-02-24 14:06 UTC, merged

2021-02-24 14:06 UTC, godrm commented
수고많으셨습니다.