Pokergameapp step5
code-squad/swift-pokergameapp pull request #193
Opened 2021-02-21 23:20 UTC by jhpark-ZG

#### 미션 진행 시 어려 웠던 점
* 게임의 방식, 인원 수를 고를 때 까지 함수 실행을 while 대기하고 싶었으나, 앱 자체가 실행이 안되어, 버튼을 선택할 때 마다 카드를 그리는 방식으로 대체하였습니다.
* 여태까지 진행한 카드 model의 Description("카드 문자열")을 view에서 받았는 데, 카드의 배열로 받아 져서 카드 한개 단위로 쪼개야 했었습니다.

#### 알게된 점
* main.storyboard에서 추가하던 Object들의 기능을 IBACTION뿐 아닌 objc로도 연결할 수 있다는 것이었습니다.

#### 개선하고 싶었던 점
* 사용자가 control 버튼 두가지 모두 누를 때까지 대기하고 함수 실행하지 않는 것이었습니다.
* segmentcontrol 부분의 함수 실행 부를 switch를 사용하지 않고 해결하는 점이었습니다.

2021-02-22 05:44 UTC, godrm requested changes
수고하셨습니다. 다음 피드백을 확인하고 개선해보세요.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +    case spade = "s", club = "c", heart = "h", diamond = "d"
아마도 카드 이미지 파일 이름 때문에 여기를 바꾼 것 같은데
이미지 파일에 대한 것은 자체는 Card 타입이 갖고 있어야 하는 속성이 아닙니다. 
하위 타입을 상위 타입에서 필요한 모든 것을 갖고 있어야 하는 게 아닙니다. 이 부분을 잘 생각해보세요.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/Players.swift
> +        print("플레이어 카운트 \(self.playerCount)")
개발 과정에서 디버깅이 필요하면 디버거 + 브레이크포인터를 활용하세요. 하위 모듈에서는 print를 직접 호출하지 않는 게 좋습니다.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/Players.swift
> +        players[index].printMyCard()
중간 단계에 있는 타입은 출력 로직을 포함하지 않고 데이터를 전달해주는 방식을 제공하는 게 좋습니다. 
print보다 다른 방식으로 처리하는 경우를 고려해야 합니다.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        self.mainCardView.subviews.forEach{$0.removeFromSuperview()}
아무리 한 줄로 표현이 가능하더라도 `{ }` 스코프가 생기면 아래로 내려쓰는 게 좋습니다.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
>          self.view.backgroundColor = UIColor(patternImage: pattern)
옵셔널 강제 언래핑!은 사용하지 않는 게 좋습니다. 옵셔널 바인딩으로 개선해보세요.  
그렇지 않으면 파일 이름이 잘못된 경우 앱이 그냥 죽어버립니다.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
>          }
이 부분의 switch-case를 제거할 수 있는 방법이 있습니다. 
gameStyle에 대한 타입을 선언해보세요. 그러면 GameType.init(segmentControl.selectedSegmentIndex) 형태로 줄일 수 있습니다.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let gameStyle = ["7 Cards", "5 Cards"]
GameType를 선언하면 여기 `["7 Cards", "5 Cards"]` 값을 하드코딩 하지 않고 생성할 수 있는 방법이 있습니다.
Card.Rank 나 Card.Suit 를 참고해서 만들어보세요.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            for j in 0..<(self.gameStyle){
여기 반복문, 배열을 탐색하는 것도 최상위 모듈에 해당하는 ViewController가 하지말고
game 이나 더 하위 모듈에서 처리하도록 하세요.
여기서는 Card별로 UIImage를 생성하기 위한 로직을 클로저 형태로 처리해보는 게 좋습니다.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let CARDHEIGHT : CGFloat = CARDWIDTH * 1.27
CGFloat 타입이 엄청 보이네요. CGFloat 와 Int, Double도 계산을 자주 할 때 쓰는 것과 최종적으로 사용하는 경우에 따라서 타입을 구분해보세요. 모두가 CGFloat여야 하는건 아닐겁니다.

2021-02-22 05:44 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let game = PokerGame.init(GameStyle: self.gameStyle, gamePlayers: self.players) //게임 스타일 결정
근데 이렇게 구현하면 drawCardinView를 호출할 때마다 game이 새로 생기는건가요?
게임은 한 번만 만들고, CardDeck 카드가 나눠줄 수 있는 동안은 계속 게임 진행을 반복할 수 있어야 할텐데요?

2021-02-28 23:45 UTC, jhpark-ZG commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let game = PokerGame.init(GameStyle: self.gameStyle, gamePlayers: self.players) //게임 스타일 결정
PokerGame.swift의 CardShake함수를 통하여 수정하였습니다.

2021-02-28 23:50 UTC, jhpark-ZG commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let CARDHEIGHT : CGFloat = CARDWIDTH * 1.27
변경 해보려고 노력해 보았는데, 지금 보다 더 나은 기준 점이 생각나지 않아서 수정하지 못했습니다. CGRect에 들어가는 4요소를 CGFloat으로 기준을 잡다보니 (기준으로 잡은 이유는 self.view.frame.width 등이 CGFloat 형이기 때문에) 이런식으로 선언하게 된 것 같습니다. 혹시 구체적인 기준을 조금 알 수 있을까요?

2021-02-28 23:59 UTC, jhpark-ZG commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            for j in 0..<(self.gameStyle){
하위 모듈에서 처리하도록 하였습니다. 다만, gamestyle에 따라, players에 따라 카드가 배치되는 방식이 바뀌기 때문에 pokergame에서 너무 많은 매개변수와, (뷰 컨트롤러) -> (포커게임) -> (게임스타일) -> (플레이어즈) -> (플레이어) -> (딜러) 이런식으로 연쇄적으로 메시지를 너무 많이 보내는 현상이 일어났습니다. 하위에서 연산해서 반환해서 주면 참 좋은데 단순히 플레이어 수가 궁금하고, 현재의 게임 스타일이 궁금한것이어서 그냥 하위로 보내서 처리하도록 하였습니다. 최상위 모듈에서는 다소 적은 매개변수를 사용하여서 조금은 위안이 되는데, 이렇게 계속 메서드를 호출하는 것이 권장하지 않는 방법인지도 사실 잘 모르겠습니다. 만약 권장하지 않는 방법이라면 이를 해결하기 위한 힌트가 있을까요?

2021-03-01 00:01 UTC, jhpark-ZG commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let gameStyle = ["7 Cards", "5 Cards"]
gamestyle.stud들 gamestyle.swift에 선언하여 만들고 해결하였습니다.

2021-03-01 00:02 UTC, jhpark-ZG commented on PokerGameApp/PokerGameApp/ViewController.swift
>          }
주신 힌트로 해결하였습니다. 올바르게 작동하는 걸 확인할 수 있었습니다.

2021-03-01 00:03 UTC, jhpark-ZG commented on PokerGameApp/PokerGameApp/Card.swift
> +    case spade = "s", club = "c", heart = "h", diamond = "d"
player가 각자 자신의 카드를 직접그리도록 변경하였고, 그에 따라 해당 문제를 class Card -> class Player로 변경하였습니다.

2021-03-01 11:31 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        players = Players.GamePlayers.allCases[segmentControl.selectedSegmentIndex]
이건 안전한 방법은 아니구요.
Players.GamePlayers.init(rawValue: segmentControl.selectedSegmentIndex) 형태가 더 안전합니다. 
참고하세요.

2021-03-01 11:32 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            for j in 0..<(self.gameStyle){
계층적으로 하위 모듈/객체를 호출하는게 당연한 겁니다. 
다만 동일한 형태 메소드를 계속해서 호출하는 건 그만큼 계층화가 덜 되서 일 수 있습니다.
하나의 타입이 바로 하위 타입 하나만 알도록 구조를 만드는 것은 상당수 괜찮습니다.

2021-03-01 11:33 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let CARDHEIGHT : CGFloat = CARDWIDTH * 1.27
중간에 계산 과정에서 CGFloat을 쓰기보다는 다른 타입을 쓰다가 마지막에 할당할 때만 넣는 게 좋습니다.

2021-03-01 11:33 UTC, merged

2021-03-01 11:50 UTC, jhpark-ZG commented
휴일에도 피드백 해주셔셔 감사합니다