Step5
code-squad/swift-pokergameapp pull request #194
Opened 2021-02-22 08:45 UTC by youngminshim-de

Step5
1. 카드 이미지들을 담을 MainStackView(Vertical) 를 만들고 그안에 라벨과 카드이미지들의 horizontal stack view 를 만들었는데, 
   label과 horizontal StackView 의 distribution 을 fillProportionally 로 설정하니 라벨의 텍스트가 짤리는 현상이 발생
   -> fillEqually로 하여 짤리는 현상은 해결했으나, 라벨의 사이즈가 불필요하게 커짐..
   -> 라벨과 horizontal stackview를 담는 vertical stackview를 추가하여 현상을 해결해 보려 했으나 현상동일..

2. stackview를 이용하여 자동으로 이미지들이 정렬이 되긴하지만, 뭔가 detail한 부분을 하나하나 바꾸기에는 어떤 방법으로 바꿔야 하는지 모르겠습니다..

2021-02-22 08:48 UTC, godrm commented
> Step5
> 
> 1. 카드 이미지들을 담을 MainStackView(Vertical) 를 만들고 그안에 라벨과 카드이미지들의 horizontal stack view 를 만들었는데,
>    label과 horizontal StackView 의 distribution 을 fillProportionally 로 설정하니 라벨의 텍스트가 짤리는 현상이 발생
>    -> fillEqually로 하여 짤리는 현상은 해결했으나, 라벨의 사이즈가 불필요하게 커짐..
>    -> 라벨과 horizontal stackview를 담는 vertical stackview를 추가하여 현상을 해결해 보려 했으나 현상동일..
> 2. stackview를 이용하여 자동으로 이미지들이 정렬이 되긴하지만, 뭔가 detail한 부분을 하나하나 바꾸기에는 어떤 방법으로 바꿔야 하는지 모르겠습니다..

네. 아직 뷰를 체계적으로 쌓는 방법이 익숙하지 않아서 그런겁니다. 뷰와 관련해서는 다시 한 번 챙겨봅시다. 
이번 단계에서 뷰까지 다 챙겨서 살펴보면 시간이 너무 오래 걸릴 것 같아요. 
간단하게는 UIView를 한 단계 포함하면 좀 더 수월해집니다.

2021-02-22 08:57 UTC, godrm requested changes
다음 피드백을 확인하고 개선해보세요.

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/MainViewController.swift
> +    func addCardImg(stackView: UIStackView, player: Player) {
setBackgroundImg, addCardImg 단어를 줄여서 표기하기 보다는 단어 자체를 그대로 써주는 게 좋습니다.
간혹 다른 의미의 다른 단어와 헷갈리기도 합니다.

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/MainViewController.swift
> +            stackView.addArrangedSubview(createImgView(name: "\(cardName).png"))
클로저를 사용했는데 player 카드를 가져오는 게 아니라 player에게 곧 바로 요청하는 게 좋습니다. 
`player.XXX { }` 형태가 되어야겠죠? 그러면 getXXX() 이런 함수가 없어도 됩니다.

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/MainViewController.swift
> +            stud = .five
여기도 switch-case 구문을 제거할 수 있습니다. 
GameType.init(value.selectedSegmentIndex) 형태로 표현할 수 있습니다.
changeGameType(value: UISegmentedControl) <--- value 보다는 sender가 좀 더 익숙한 표현입니다. 값이 아니라 객체거든요.

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/MainViewController.swift
> +        resetPockerGame(game: PockerGame(number: self.participantType, number: stud))
이런 부분도 고민해보세요. 매번 게임 객체를 새로 만들어야 하나?
아니면 바뀐 타입만 바꾸면 게임은 계속할 수 있나?

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Card.swift
>      }
오잉? description이 왜 사라졌죠?

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Participants.swift
> +    func getParticipants() -> [Participant] {
Participants에서 `getParticipants() -> [Participant]` 메소드를 제공해주는 게 아니라
외부에서 이 배열로 무엇을 할지 기능을 메소드로 제공해주세요.
탐색이 필요하면 클로저를 매개변수로 받아서 탐색할 수 있도록 해주세요.

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Player.swift
> +    case Pariticipant4 = "참가자4"
이런 문자열 표현을 하드코딩하는 것은 좋지 않습니다.
100명이면 100개를 미리 작성할껀가요? 개발자가 많은 것을 하기보다는 기계가 일을 하도록 시켜보세요.

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Player.swift
> +        return name.rawValue
getCard() , getName() 속성을 가져가지 말고 Player가 Card 배열과 이름으로 뭔가 하도록 메소드를 생성하세요.

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
> +        return self.rawValue
rawValue를 제공하기 보다는 여기서도 메소드를 제공하는 게 좋습니다.

2021-02-22 08:57 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
> +        self.numOfCard = ofCard.value
GameType을 선언했으면 numofCard는 Int 타입이 아니라 계속 GameType 타입을 사용하는 게 좋습니다.

2021-02-22 15:27 UTC, youngminshim-de commented on PokerGameApp/PokerGameApp/Model/Card.swift
>      }
해당코드의 존재의미가 없다고 판단해서 지웠습니다. (step 초반에는 이모지를 출력하여 보여줄 일이 있었지만, 현재는 의미가 없어보이는데 혹시 다음 스텝의 승자판단 예시 때문일까요?)
description 을 그대로 쓸 경우 카드이미지와 Shapes을 매칭시킬 때 한번의 작업이 더 필요한데,
description 을 계속 써야 하는 이유가 혹시 있을까요?

2021-02-23 01:50 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Card.swift
>      }
물론 description 자체는 개발 과정에서 필수 요소는 아닙니다. 객체가 가진 정보를 String 문자열로 설명하고 표현해주는 것 뿐이죠. 
기본적으로 description을 기반으로 로직을 구현하는 것은 좋은게 아닙니다. 왜냐하면 내부 속성이나 설명이니까 언제든지 바뀔 수 있죠.
`description을 그대로 써서 카드 이미지 파일과 매칭하라`는 게 아닙니다. 

기능 요구사항을 만족한다는 것을 봤을 때 필요없으면 지워도 됩니다만
우리가 학습하는 과정에서는 이전 요구사항을 최대한 유지하는 상태로, 다음 스텝에서 변경되는 부분을 작성해보세요.
제가 스텝을 나눠놓은 것은 작업하는 단위를 하루 단위 정도로 나눠놓은 것일 뿐,
전체가 하나의 요구사항이라고 생각해도 됩니다. 그것을 작은 단위로 나눠서 PR을 보내고 있는거죠. 

기존 요구사항을 만족하는 수준에서 다음 단계로 나오는 추가 요구사항을 만족하도록 개선해보는 경험이 중요해서입니다.
다음주쯤부터는 모든 요구사항을 만족하는지 확인하는 단위 테스트에 대해서 이야기할 예정입니다. 참고하세요.

2021-02-23 02:29 UTC, youngminshim-de commented
Comment 들 반영하여 다시 Push 했습니다.

2021-02-23 02:45 UTC, godrm requested changes
코멘트에 대한 개선사항이 있으면 관련 코멘트마다 댓글을 남겨주면 해결했는지 안했는지 판단하기 쉽습니다. 
아직 반영이 안된 사항이 있는 것 같습니다. 다음 피드백을 한 번 살펴보세요.

2021-02-23 02:45 UTC, godrm commented on PokerGameApp/PokerGameApp/MainViewController.swift
>      }
여기 함수들 사이에 공백이 없어서 한 덩어리로 보입니다.
공백이나 빈 줄도 개발자 의도를 표현하는 수단입니다. 항상 일관성 있게 표현해주세요.

2021-02-23 02:45 UTC, godrm commented on PokerGameApp/PokerGameApp/MainViewController.swift
>          let participantTypeSegment = UISegmentedControl(items: ["2명", "3명", "4명"])
여기처럼 문자열을 하드코딩하는 것도 지양하세요. 직접 값을 작성하지마세요.
아마도 GameType, ParticipantType 에서 CaseIterable 프로토콜로 해결할 수 있을 겁니다.

2021-02-23 02:45 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Player.swift
>      private var name: PlayerType
Player와 Dealer를 구분할 때 지금처럼 PlayerType을 선언하고 type으로 넣는 게 아니라
수퍼 클래스나 프로토콜로 상위 개념을 만들고, 하위에 Player와 Dealer 타입을 선언해서 세부적인 동작을 구분하는 구조가 좋습니다. 
타입으로 구분하면 타입으로 구분하려는 코드가 생깁니다. 
이렇게 생각해보세요. 딜러, 참가자 이외에 다른 타입이 추가되거나 삭제되서 그 타입만 규칙이 달라져야 한다면 고쳐야 하는 곳이 얼마나 생기는지 고민해보면 도움이 될 겁니다.

2021-02-23 02:45 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
> +        }
init을 따로 선언해주지 않아도 5 나 7을 넣으면 되지 않던가요? 다른 값은 생성이 안되구요?

2021-02-23 02:45 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
>      }
rawValue를 제공하는 것보다 rawValue로 처리하는 로직을 메소드로 제공해주는 접근을 항상 고민하세요.

2021-02-23 04:03 UTC, youngminshim-de commented on PokerGameApp/PokerGameApp/MainViewController.swift
>          let participantTypeSegment = UISegmentedControl(items: ["2명", "3명", "4명"])
CaseIterable protocol을 이용하여 allItems 라는 함수를 통해 원하는 형태의 [String]을 리턴하도록 만들었습니다.

2021-02-23 04:04 UTC, youngminshim-de commented on PokerGameApp/PokerGameApp/MainViewController.swift
>      }
넵 조금더 신경 써서 표현하도록 노력하겠습니다

2021-02-23 05:31 UTC, youngminshim-de commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
> +        }
init(sender.selectedSegmentIndex) 을 초기화할 때 sender.selectedSegmentIndex 의 값이 0부터 시작해서 Type의 rawValue 값과 상이해 init 함수를 다시 선언해주었습니다.

init을 따로 선언해주지 않아도 5나 7을 넣으면 된다는게 어떤의미인지 잘모르겠습니다.. 

init 함수는 switch문보다 조금 더 간결한 형태로 변경해봤습니다.

2021-02-23 05:32 UTC, youngminshim-de commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
>      }
불필요하게 rawValue를 return 하던것을 SegmentControl의 Item 으로 바로 쓸수있도록 메소드를 제공해줬습니다.

2021-02-23 05:38 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
> +        }
enum에 init 구현하지 않아도 init(rawValue:) 할 수 있는지 확인해보세요.

2021-02-23 07:11 UTC, youngminshim-de commented on PokerGameApp/PokerGameApp/Model/Player.swift
>      private var name: PlayerType
Player 는 Participant 와 Dealer 를 포함하는 수퍼 클래스이고, Type 은 이름을 넣어주기 위함이었습니다.
제 생각은 Player(수퍼클래스) 에서 공통적인 부분을 구현하고, Participant, Dealer (서브클래스) 에서는 공통되지 않는 동작을 구현하는 것이 더 효율적이라 생각했습니다.
질문)
1. 그럼 프로토콜을 만들어놓고 서브클래스에서 동작들을 구현하는 구조가 더 낫다는 말씀이신가요? (추후에 다른 타입이 추가되었을 때
해당 타입의 서브클래스만 추가하면 되니까)

2. 아니면 주석처리 된 부분 PlayerType을 없애고 공통적인 부분은 수퍼클래스에서 구현을 해놓고 서브클래스에서는 추가적인 동작을 구현 하는것이 더 좋은지?

2021-02-23 07:14 UTC, youngminshim-de commented
[Min] Step5 
1. 함수들 사이에 공백을 주어 함수들이 구분될 수 있도록 수정
2. init 함수를 아예 없애지는 않고 init 함수에서 switch 문을 제거하고 수정
3. Player(수퍼클래스) 를 프로토콜로 변경, PlayerType(dealer, participant) 삭제

2021-02-23 07:56 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/Player.swift
> +//}
사용하지 않는 코드는 주석으로 남기지 말고 과감하게 지우세요.

2021-02-23 07:58 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
> +    }
이렇게 init()을 아예 구현하지 않아도 된다는 겁니다. 
그냥 선언하지 않으면 enum 타입의 init은 동일하게 동작합니다.
`GameType.init(rawValue: 5)` <--- .five 가 생기구요. 
`GameType.init(rawValue: 1)` <--- nil 이 됩니다. 
직접 구현하지 않아도 된다가 핵심입니다.

2021-02-23 07:59 UTC, godrm commented on PokerGameApp/PokerGameApp/Model/PockerGame.swift
> +        return GameType.allCases.map({$0.description})
allItems 같은 static 타입 메소드는 좋습니다. 다만 description을 바꾸기 보다는 여기에서 붙였으면 더 좋았을 것 같네요.

2021-02-23 08:00 UTC, godrm commented
제 피드백에 맞춰서 딱 해당 부분만 코드를 개선하려고 하기보다는 해당 코멘트가 왜 필요한지, 바꾸는 게 왜 중요한지 맥락을 이해하는 게 더 중요합니다. 그러다보면 기존의 리뷰한 내용까지 흔들리게 수정하는 경우가 생길 수 있습니다. 수고많이하셨습니다.

2021-02-23 08:00 UTC, merged