Pokergameapp step5
code-squad/swift-pokergameapp pull request #196
Opened 2021-02-23 09:14 UTC by Sonjh1306

[Aiden] Step-5 요구 사항을 만족하는 포커게임 결과 화면

- [x] 카드 이미지 Assets 추가(파일 이름 그대로 사용)
- [x] Card 객체와 이미지 파일명을 매치하는 방법을 구현
- [x] CardDeck 인스턴스를 만들고 랜덤으로 카드를 섞고 출력 화면처럼 보이도록 개선
- [x] 카드 정보를 화면에 카드 이미지로 표시
- [x] 앱에서 Shake 이벤트를 발생하면 랜덤 카드를 다시 섞고 다시 동작하도록 구현

- 학습 키워드: 스택뷰 구성하기, 객체 지향적인 코드 작성, 클로저 사용
- 고민과 해결: 하나하나 세부적인 것까지 신경쓰기에는 버겁다고 느껴져서  일단 결과 화면을 출력 하는 것을 목표로 구현하고 리뷰를 통하여 추가적인 학습을 해야겠다라는 생각으로 진행했습니다. Private 으로 지정된 내용들을 읽어오기 위하여 클로저를 사용해야 한다는 것은 수업과 다른 분들을 통하여 이해는 했지만 쉽지 않다고 느껴져 private(set)을 통해 값을 읽어서 구현을 하였습니다. 이미지 파일을 추가하고 Card 객체와 이미지 파일명을 매치하는 방법을 고민하다가 Card 내의 문자를 변환시켜주는 함수들을 추가하여 매치를 시킬 수 있도록 하였습니다. 뷰의 구성은 전체적인 큰 스택뷰 내의 라벨 스택뷰 + 카드이미지 스택뷰로 구성을 하였으며 세그먼트컨트롤 같은 경우엔 코드로 구현하지 않고 스토리보드에서 만들어줬고 오토레이아웃을 적용시켰습니다. 
- 질문거리: 상위 모듈과 하위 모듈 간의 객체 지향적인 관계라고 해야할까요?… 계속 해보려고는 하는데 머릿 속으로 그려지지가 않아 많이 헤메는 것 같습니다. 미션을 하면서 학습하는 방법 외에 익숙해지기 위해 따로 학습 하는 방법이 있을까요?

2021-02-23 09:16 UTC, godrm commented
참고로 PR 제목은 `Pokergameapp step5` <---- 이 부분을 말한거에요 :)

2021-02-23 09:38 UTC, godrm requested changes
다음 피드백을 확인해서 개선해보세요.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/Card.swift
> +        }
이미지 파일 이름을 매칭하기 위해서 Card를 수정할 지, 아니면 상위에 만들지 고민해볼 필요가 있습니다.
이미지 파일은 Card 모델에 필요한 값인지 아닌지 중요한 기준이 됩니다. 
그런 의미에서 새로 추가한 메소드말고 다른 방법도 있는지 고민해보세요.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/Dealer.swift
> +    private(set) var dealer: [Card]
private 보다는 private(set) 방식도 조심스럽게 사용하세요.
이렇게 속성 값을 가져가기 보다는 Dealer가 배열에 접근하면서 처리할 수 있는 메소드를 제공해주는 게 좋습니다.
클로저 형태로 매개변수를 넘기는 메소드를 만들어보세요.
덧붙여서 배열 이름도 dealer는 이상한거 아닐까요?

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/PokerGame.swift
> +    private(set) var dealer: Dealer
이번에는 players 와 dealer까지 열어주고 있네요.
PokerGame에도 클로저 형태를 전달하는 메소드를 추가해보세요.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +//    }
사용하지 않는 코드는 주석으로 남기지 말고 과감하게 지우세요.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let pokerGame = PokerGame(playerCount: PokerGame.PlayerCount(rawValue: playerCount.rawValue)!, cardStud: PokerGame.CardStud(rawValue: cardStud.rawValue)!)
강제 언래핑 보다는 안전하게 처리하도록 개선해보세요. 
if let, guard let, nil 연산자 등이 있습니다.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        self.pokerGame = pokerGame
이 줄은 크게 의미가 없네요.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +            break
여기 switch-case 들은 PlayerCount.init() , CardStud.init() 으로 대체해서 표현해보세요.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        stackView.addArrangedSubview(makeLabelStackView(text: "Dealer"))
"Player\(num+1)" 이나 "Dealer" 값도 여기 하드코딩하는 게 아니라 Players 나 Dealer에서 처리하도록 하는게 좋습니다.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        // 옵셔널 바인딩
이런 주석은 구체적으로 아무런 정보를 제공해주지 못해서 불필요한 주석입니다.

2021-02-23 09:38 UTC, godrm commented on PokerGameApp/PokerGameApp/ViewController.swift
> +        let cards = player.player
`player.player` 값 이름이 어색합니다. 
이렇게 값을 가져오는 게 아니라 이 부분에서 player.xxx { } 형태로 아래 뷰를 생성하는 코드를 전달하면 됩니다.

2021-02-24 06:21 UTC, Sonjh1306 commented
다음 PR부터는 제목 제대로 작성하겠습니다. 리뷰해주신 내용들 최대한 리팩토링 해보려고 노력했습니다.  
1. 이미지 파일 매칭을 위해 Card를 수정할지 또는 상위에 새로 매칭할 수 있도록 구현할지에 대해선 현재의 저의 견해로는 Card 모델을 수정해도 나쁘지 않다고 생각이 드는 것 같습니다. 그래도 추가적으로 고민을 해보도록 하곘습니다.
2. private 또는 private(set) 두 방식 모두 조심스럽게 사용하겠습니다. private(set)을 사용하지 않기 위해 클로저 형태로 매개변수를 넘기는 메소드를 구현해보았습니다.  뭔가 새로운 걸 구현하려하니 막연해서 다른 분들의 코드를 최대한 빌려와서? 구현하며 이해하려고 했습니다.
3. 사용하지 않는 코드는 지웠고 앞으로 주석으로 남겨두지 않고 바로바로 과감하게 지우겠습니다.
4. 강제 언래핑을 옵셔널 바인딩으로 수정하였습니다. 
5. 세그먼트컨트롤을 switch-case 문으로 변경하는 것이 아닌 열거형의 init()으로 변경했습니다.
6. 하드코딩 부분은 많이 고민을 했는데 각각 Player와 Dealer의 description을 활용하는 것도 괜찮을 것 같아 수정하였습니다.

2021-02-24 06:56 UTC, godrm commented
수고하셨습니다!

2021-02-24 06:56 UTC, merged